# Generated by Django 5.0.4 on 2024-04-17 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbooking', models.DateField()),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='P_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_amount', models.CharField(max_length=2000, null=True)),
                ('p_date', models.CharField(max_length=2000, null=True)),
                ('p_status', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pic', models.ImageField(max_length=1000, upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.login')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=500)),
                ('dosage', models.CharField(max_length=400)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(default=False, max_length=200)),
                ('quantity_available', models.IntegerField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('usage_instructions', models.TextField(blank=True, null=True)),
                ('certifications', models.ImageField(default=True, max_length=1000, upload_to='')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=2000, null=True)),
                ('product_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.category')),
            ],
        ),
        migrations.CreateModel(
            name='P_bookingchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_amount', models.CharField(max_length=225)),
                ('quantity', models.CharField(max_length=225)),
                ('P_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.p_booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('treatment_type', models.CharField(choices=[('panchakarma', 'Panchakarma'), ('vamanan', 'Vamanan'), ('snehavasthy', 'Snehavasthy'), ('nasyam', 'Nasyam'), ('shirodhara', 'Shirodhara'), ('tharpanam', 'Tharpanam'), ('putapakam', 'Putapakam')], max_length=100)),
                ('food_plan', models.CharField(choices=[('regular', 'Regular'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-Free')], max_length=100)),
                ('number_of_days', models.PositiveIntegerField(choices=[(3, '3 days'), (5, '5 days'), (7, '7 days')])),
                ('status', models.CharField(default='pending', max_length=100)),
                ('user', models.CharField(default='0', max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.room')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timefrom', models.TimeField()),
                ('timeto', models.TimeField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.doctors')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.schedule'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pic', models.ImageField(max_length=1000, upload_to='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.login')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.seller'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.subcategory'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.login')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.users')),
            ],
        ),
        migrations.CreateModel(
            name='paymentss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=500)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.booking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=2000, null=True)),
                ('py_status', models.CharField(max_length=225, null=True)),
                ('P_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.p_booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.users')),
            ],
        ),
        migrations.AddField(
            model_name='p_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.users'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.doctors')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.users')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.users'),
        ),
    ]
